spring.application.name=rag-kyc-compliance
spring.ai.openai.api-key=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
spring.ai.openai.chat.model=gpt-3.5-turbo
server.port=8081
